### ISSUE TITLE
JS error on pages without accordion

### ISSUE THREAD

**Issue by formspiel** [benbowes/Accessible-Accordian-Class-Pure-JS-CSS#1]
Hi Ben,

thanks for you gorgeous accordion script! I used your implementation for a tiny landing/faq-page (not public at the moment—NDA :-(  ).

• Your script is the only script on the page
• I embed it and the end of the page (before </body>)

On the page with the accordion itself everything is working fine but on other pages i get the error message on Chome 46

```
Uncaught TypeError: Cannot read property 'select' of undefined
   myAPP.init @ all.js:115 (this.accordionContainer.panels[0].select();)
   window.onload @ all.js:119 (myAPP.init();)
```

Do you have an idea? It would be great to have an empty console ;-)

Best,
Andreas

**Comment by benbowes** [comment]
Hi Andreas, 

It sounds like you need to find a way to run it only on the page/view that needs it.

Also are you using the classes `.accordion-panel__heading` or `.accordion-panel__content` anywhere else?

Ben
