### ISSUE TITLE
css class name bug `-` ? `_`

### ISSUE THREAD

**Issue by xgqfrms** [benbowes/Accessible-Accordian-Class-Pure-JS-CSS#2]
# css class name bug `-` ? `_`

![image](https://user-images.githubusercontent.com/7291672/41632848-7781c3e4-746e-11e8-80cc-756e6d4331f4.png)

![image](https://user-images.githubusercontent.com/7291672/41632930-d8894cc0-746e-11e8-98e6-21bd2c9d1d5b.png)

```js

classnames = "className1 className2 className3 ";
// "className1 className2 className3 "

this.className = "f10_latest-news_fixed-width abc-xyz className1";
// "f10_latest-news_fixed-width abc-xyz className1"

this.className = this.className.replace(new RegExp('(^|\\b)' + classnames.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
// " f10_latest - news_fixed - width   abc - xyz    "

```

**Comment by benbowes** [comment]
Thanks @xgqfrms 

I will remove these methods in favour of using the inbuilt classList https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

When I wrote this the above was not well supported, now it is.

**Comment by benbowes** [comment]
I have updated `myApp.js` @xgqfrms, please let me know if you have any more problems 👍

**Comment by xgqfrms** [comment]
@benbowes 👍 you are welcome.
